### ISSUE TITLE
Swagger UI does not correctly display routes

### ISSUE THREAD

**Issue by kevinkhao** [shopinvader/odoo-shopinvader#1050]
This is potentially related to the latest changes in rest-framework. This is Swagger UI for shopinvader by itself:

![Screenshot from 2021-07-30 05-03-17](https://user-images.githubusercontent.com/19902174/127595382-aa69acf2-49dc-4334-9e0f-e6d08faef4f2.png)

This is Swagger UI for shopinvader_auth_api_key:

![Screenshot from 2021-07-30 05-02-24](https://user-images.githubusercontent.com/19902174/127595418-7437f059-c5cf-4d24-b666-2266a4931672.png)

**Comment by simahawk** [comment]
@lmignon could you check?

**Comment by lmignon** [comment]
I'll check.

**Comment by lmignon** [comment]
@kevinkhao @simahawk fixed in #1051
