### ISSUE TITLE
[14.0] duplicate key value violates unique constraint "product_product_combination_unique"

### ISSUE THREAD

**Issue by sbidoul** [shopinvader/odoo-shopinvader#1066]
I get this error when updating the `shopinvader` module in 14.0:

```
Error: duplicate key value violates unique constraint "product_product_combination_unique"
DETAIL:  Key (product_tmpl_id, combination_indices)=(29, ) already exists.
```

There are exotic things going on in https://github.com/shopinvader/odoo-shopinvader/blob/14.0/shopinvader/demo/product_product_demo.xml (WTH it this `<function>` tag ?) which I don't quite grok.

Does anyone know something about it ? @sebastienbeau may be as you touched that part recently ?

**Comment by sbidoul** [comment]
Related to https://github.com/shopinvader/odoo-shopinvader/pull/936 ?

**Comment by sebastienbeau** [comment]
I will look at it tomorrow

**Comment by sebastienbeau** [comment]
Note the function have been added here : https://github.com/shopinvader/odoo-shopinvader/pull/503/files#diff-a29a2e3914f7f47c2038ccd93e0179e89f6f50d7e0451636f45de655ab42dc35

**Comment by sebastienbeau** [comment]
can you test my fix  : https://github.com/shopinvader/odoo-shopinvader/pull/1067 ?
