### ISSUE TITLE
[14.0] `'shopinvader.backend' object has no attribute 'auth_api_key_id'`

### ISSUE THREAD

**Issue by Mat-moran** [shopinvader/odoo-shopinvader#1098]
Hi, 

I am starting with shopinvader, I have configured: 

- Algolia backend
- Locomotive server
- Odoo server in version: 14.0

When pressing the ` Reset site settings` or `Synchronize Metadata` I get the following error related with this code 

```
Error:
Odoo Server Error

Traceback (most recent call last):
  ...
  File "/opt/odoo/auto/addons/shopinvader_locomotive/component/shopinvader_site_export_mapper.py", line 81, in erp_config
    erp["api_key"] = record.auth_api_key_id.key
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'shopinvader.backend' object has no attribute 'auth_api_key_id'
```
In this part of the code 
https://github.com/shopinvader/odoo-shopinvader/blob/c19e519e37cba2d3aea08d1cbdbf682e3070e928/shopinvader_locomotive/component/shopinvader_site_export_mapper.py#L78-L86

it is checking for the `auth_api_key_id` but I did not see this parameter in the definition of the class `ShopinvaderBackend`.

The module that implement this attribute is `shopinvader_auth_api_key` but it is not required so... 

Should the above module be required or is a bug in the `shopinvader_site_export_mapper.py`? Also can be a misconfiguration from my side?

Thanks and regards. :smile:

**Comment by simahawk** [comment]
@Mat-moran you got it :) The API key part has been refactored out of the base module recently but `shopinvader_auth_api_key` has not been added as dependency to `shopinvader_locomotive`.

I've just opened #1099 on the fly. Should fix it.

**Comment by Mat-moran** [comment]
Thanks @simahawk I close the issue then.

**Comment by rousseldenis** [comment]
@simahawk I think something different should be done as auth method could be something else.

I thought about a generic method to export auth_details or something like that.

@lmignon

**Comment by lmignon** [comment]
@rousseldenis At this stage only auth_api_key is supported and required by locomotive....

**Comment by rousseldenis** [comment]
> @rousseldenis At this stage only auth_api_key is supported and required by locomotive....

Yes, indeed, I thought about that just after writing.
