### ISSUE TITLE
[14.0] shopinvader_invoice: Restore initial service

### ISSUE THREAD

**Issue by rousseldenis** [shopinvader/odoo-shopinvader#1100]
To not break initial services, I propose to restore invoice state with a mapping for 'posted' => 'open' and to add payment_state as a separate entry.

**Comment by Mat-moran** [comment]
I was going to put an issue because the `.../invoices` and `.../invoice` endpoints only give the invoices with the `payment_state_label = Paid`.

It is something related with this?

It is a bug or it is the expected behaviour?
