### ISSUE TITLE
[14.0] Unable to connect Odoo backend with locomotive server (neither test the api)

### ISSUE THREAD

**Issue by Mat-moran** [shopinvader/odoo-shopinvader#1102]
Hi I am having troubles connecting Odoo with Locomotive server.

I have everything set-up, also I can see the binded products in Algolia but I can not connect odoo with Locomotive.  With respect to the locomotive an odoo connection I have set-up:

- The Administrator `Api Key` in `Settings > Technical > Auth Api Key` and I have selected it in the shopinvader backend.
- The `email`, `Locomotive's api key`, and `handle` set-up correctly, also the `location` of the locomotive server.

Nothing happend in my Locomotive server when I click `Reset site settings` or `Synchronize Metadata`. No configuration is pushed to Locomotive.

Odoo version: V14.0

Also I am trying to test the shopinvader api without any succes maybe both are related?

 When I try to test the api with the `base_rest` module I get the error

__Firefox:__ ` TypeError: NetworkError when attempting to fetch resource.`

__Chrome:__

```
Failed to fetch.
Possible Reasons:

CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.
```

Am I doing something wrong? Need I to configure something else in the odoo server? It seems that everything is ok but...

Thanks in advance and regards.

**Comment by Mat-moran** [comment]
I think I am going to leave Locomotive aside... Closing the issue.

**Comment by simahawk** [comment]
@Mat-moran how have you set up the services? Using `docker-compose`?

**Comment by Mat-moran** [comment]
Hi @simahawk thanks for the reply.

Not, I was using a server for Odoo and other for Locomotive.
