### ISSUE TITLE
Use widget boolean_toggle instead of button toogle_active in product.template view in the binding tab

### ISSUE THREAD

**Issue by sebastienbeau** [shopinvader/odoo-shopinvader#1133]
using this new widget will give a better UI experience
![image](https://user-images.githubusercontent.com/1164578/136152881-6c317320-339f-4b61-bfe7-0505f2a50395.png)

**Comment by sebastienbeau** [comment]
Also when we create a binding the binding is inactive by default we have to fix it, it should be active by default

**Comment by kevinkhao** [comment]
https://github.com/shopinvader/odoo-shopinvader/pull/1134
