### ISSUE TITLE
Other opoen source search engine

### ISSUE THREAD

**Issue by Mat-moran** [shopinvader/odoo-shopinvader#1178]
Searching google I found this search engine.

I am already using algolia because it is very simple to use and they have a very great admin experience, but this seem very nice  search engine too an is open source.

Just to let you know this one.

https://typesense.org/

**Comment by simahawk** [comment]
Thanks for reporting this. Could you move it to https://github.com/OCA/search-engine/ ?

**Comment by Mat-moran** [comment]
Done
