### ISSUE TITLE
Public wishlists

### ISSUE THREAD

**Issue by qgroulard** [shopinvader/odoo-shopinvader#1249]
Many eshops feature a share wishlist mechanism.
Allowing other people to visualize your wishlist via an url.

I am trying to achieve that with shopinvader, but I cannot access wishlist without passing the header PARTNER-EMAIL.
Is there a way to publicly get wishlists ?

**Comment by simahawk** [comment]
ATM to get a wishlist you need a backend and a customer.
In fact the `partner_id` on `product.set` is not required and you could play with this domain https://github.com/shopinvader/odoo-shopinvader/blob/14.0/shopinvader_wishlist/services/wishlist.py#L282.
We could have flag on the backend to allow public wishlists.
Then you have to change this https://github.com/shopinvader/odoo-shopinvader/blob/14.0/shopinvader_wishlist/services/wishlist.py#L51.
You'll need also a cron to cleanup abandoned wishlists.

**Comment by qgroulard** [comment]
Hi @simahawk
Thanks for the answer.
Actually I still want the wishlists to belong to a customer.
One possible use case would be:

I like reading books.
I create a wishlist on a famous eshop with books that I'd like to read.
This wishlist belongs to me and I can access it on my profile.
I get a link to share with my family and friends so that they can get access to my wishlist.
My wife clicks on this link and can easily add items from my wishlist to her own cart.
She makes me a nice gift :gift:

Problem is currently my wife can't access to a wishlist that does not belong to her.
I'd like to make this possible.

**Comment by simahawk** [comment]
Hmm I see. Then you should use some sort of token to allow sharing / viewing it as the portal does.
