### ISSUE TITLE
Send email notifications

### ISSUE THREAD

**Issue by cramosh** [shopinvader/odoo-shopinvader#1257]
When shopinvader must detect the Cart Confirmation to send the mail. At what point does the action jump?

**Comment by Mat-moran** [comment]
It is done with the `sale_automation_workflow` in combination with the `base_automation`.

With the first you can define the automatic actions of your workflow, for example cart confirmation when the cart is in an specific step.
 
With the second you can assign automatically this workflow to a certain orders for example with a specific backend on creation.
