### ISSUE TITLE
How to confirm a cart?

### ISSUE THREAD

**Issue by Mat-moran** [shopinvader/odoo-shopinvader#1260]
Hi I am trying to find how to confirm a cart but I can not find anything about that.

How do you validate a cart when the customer click checkout?

Thanks in advance.

**Comment by HviorForgeFlow** [comment]
take a look on sale_automatic_workflow

**Comment by Mat-moran** [comment]
It is an awesome module, very very nice.

Combining it with the `base_automation` it is possible to apply the workflow to the orders created from a specific backend.

Thanks!
