### ISSUE TITLE
active_shipping client

### ISSUE THREAD

**Issue by rvalyi** [shopinvader/odoo-shopinvader#128]
wrap https://github.com/Shopify/active_shipping in a microservice much like https://github.com/akretion/boleto_cnab_api
and have a client for it (much like https://github.com/akretion/odoo-boleto-cnab ) to consume it from ShopInvader. May be useful for places where we didn't built python shipping libraries when great ones by Shopify may exist. Possibly useful for the USA and Brazil.

Would give us support for:
```
USPS
USPS Returns
FedEx
Canada Post
New Zealand Post
Shipwire
Stamps
Kunaki
Australia Post
```

active_shipping gives us rates and tracking but unlike https://github.com/OCA/delivery-carrier it doesn't print labels. 

As for Brazilian Correios, it was just broken and this link may be interesting (possibly we fix ActiveShipping):
https://github.com/Shopify/active_shipping/pull/556

**Comment by simahawk** [comment]
still valid?
