### ISSUE TITLE
[RFC] Test 14.0 branch with python 3.8 

### ISSUE THREAD

**Issue by sbidoul** [shopinvader/odoo-shopinvader#1377]
Hi everyone,

Since we are going to add some FastAPI services on the 14.0 branch and python 3.6 is very old for FastAPI (it kind of works but is less comfortable), we are considering testing the 14.0 branch with python 3.8 so we have access to more fastapi and pydantic features.

Is that a problem for anyone? In other words, is there anyone running shopinvader 14.0 on python 3.6 or 3.7?

**Comment by sbidoul** [comment]
@simahawk @ivantodorovich @sebastienbeau @hparfr

**Comment by hparfr** [comment]
python3.8 looks good to me

**Comment by rvalyi** [comment]
Hello @sbidoul Python 3.7 has just been set End Of Life yesterday. Odoo v14 is probably still in its early years so eventually this question is broader than just Shopinvader: I guess soon enough we may question moving GitHub Actions to a Python 3.8 container for many if not all v14 OCA repos... 

BTW, I recently tried to run the CI on Python 3.7 for Odoo 12 and there is no container using Python 3.7 for Odoo 12. May be that would also be a great option cause Python 3.6 is now causing more and more troubles and Odoo V12 is known to run just fine on Python 3.7.

**Comment by sbidoul** [comment]
> there is no container using Python 3.7 for Odoo 12

I'll be happy to merge a PR to add it to oca/oca-ci.

For OCA if we change the tested python version, we should also update the default requires-python metadata in the wheels we publish.

**Comment by sbidoul** [comment]
I created #1379 to test the 14.0 branch with python 3.8 instead of 3.6.
