### ISSUE TITLE
Generating automatic API documentation for Shopinvader

### ISSUE THREAD

**Issue by sebastienbeau** [shopinvader/odoo-shopinvader#14]
# Context

For a better security I have introduced the concept of validator for the services exposed to the controller.
See an example here : https://github.com/akretion/shopinvader/blob/8.0/shopinvader/services/cart.py#L79

This validator are based on cerberus doc here : http://docs.python-cerberus.org/en/stable
It will be great to generate an automatic documentation based on this validator as they specify explicitly the value possible for each api.

# Proposal

The idea will be to create a specific page (an odoo controler) accessible by a logged user that will generate for a specific backend the documentation for all the shopinvader api by looking in the service and calling the validator method to get the schema

**Comment by sebastienbeau** [comment]
work in progress here : https://github.com/akretion/odoo-shopinvader/pull/144

**Comment by lmignon** [comment]
documentation is available via a swagger page at /api-docs
