### ISSUE TITLE
[16.0] Cart steps?

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#1511]
Any plan to add cart steps to v16?
We should probably have a base module `sale_cart_step` + `shopinvader_api_cart_step`.

**Comment by sbidoul** [comment]
I'm not aware of anything like that. Maybe @thibaultrey or @sebastienbeau ?

**Comment by simahawk** [comment]
Done here https://github.com/shopinvader/odoo-shopinvader/pull/1521

@thibaultrey @sebastienbeau any feedback would be appreciated.

**Comment by thibaultrey** [comment]
> Done here https://github.com/shopinvader/odoo-shopinvader/pull/1521
> 
> @thibaultrey @sebastienbeau any feedback would be appreciated.

We haven't needed it in the last projects, is this concept still useful?
