### ISSUE TITLE
base_rest: RFC: Improve request/response Schema description

### ISSUE THREAD

**Issue by lmignon** [shopinvader/odoo-shopinvader#154]
## Current context

In base_Rest, information exchanged by services is validated according to a Cerberus schema defined as dict.

```python
    address_request_schema = {
        'name': {'type': 'string', 'required': True, 'empty': False},
        'street': {'type': 'string'},
    }
```

Defining such schemas could become boring and lead to a hard to read/maintain result when the schema is complex. This kind of definition is also hard to extend, reuse etc...

## Proposal

Odoo already provides a clean api to define models. This API provides a pythonic way to define fields and relation between models. It also provides a clean way to override and extend models across modules. The Idea is to define a new base class based on BaseModel to define the messages exchanged by the services.

```python

class RestModel(models.BaseModel):
    _name='rest.model'
    
    def from_json(self, json_data):
        return self.new(....)

    def to_json(self):
        return {}      
    
    def validate(self):
        return True

    def to_json_schema(self):
        """ Return the definition of the model as json schema
        see http://json-schema.org/
        """
        retrun {}


class AddressRequest(RestModel):
    _name = 'address.request'

    name = fields.Char(required=True)
    street = fields.Char()

    ....
```
### Expected benefits:

* More modular
* Easier to extend / reuse / redefine
* Easier to manipulate into the services implementation. `my_address['name'] vs my_address.name`
* Easier to document (thanks to `string` and `help`attributes of the fields we'll be able to provide a description into the json schema)
* ....

**Comment by lmignon** [comment]
ping @sebastienbeau @sbidoul @Cedric-Pigeon @acsonefho

**Comment by sbidoul** [comment]
Sounds like a great idea at first glance. 

Documentation and reuse are strong arguments. It would also become easier to annotate services with request/response models instead of the current implicit properties. m2o, m2m should work too (for json dicts and lists respectively). Selections for enums.

Perhaps one should quickly scan the Cerberus schemas we currently have in actual services, to check if the Odoo models are expressive enough to cover all our needs.

**Comment by lmignon** [comment]
@sbidoul 
> It would also become easier to annotate services with request/response models instead of the current implicit propertie

Indeed, with a way to say that the request  / response is a list or not (default)

```python

    @restapi.method(
        request='address.search.request',
        request_is_list=False, # default 
        response='address.info',
        response_is_list=True,
    )
    def search(self, params):
        items = self.env['res.partner'].search(...)
        result = []
        for item in items:
            info = self.env['address.info'].new()
            info.name = item.name
            ....
            result.append(info)
        return result
```

**Comment by sebastienbeau** [comment]
:+1:

**Comment by lmignon** [comment]
moved to https://github.com/OCA/rest-framework/issues/2
