### ISSUE TITLE
Finish the connection with locomotive

### ISSUE THREAD

**Issue by sebastienbeau** [shopinvader/odoo-shopinvader#17]
The code for the connection is not clean at all and should be refactored and maybe extracted in a lib.
See the code in the adapter here : https://github.com/akretion/shopinvader/blob/8.0/connector_locomotivecms/unit/adapter.py

**Comment by rousseldenis** [comment]
@sebastienbeau Is this still applicable ?

**Comment by sebastienbeau** [comment]
it's done
