### ISSUE TITLE
Url key computation raise Error on product modification (multicompany context)

### ISSUE THREAD

**Issue by rousseldenis** [shopinvader/odoo-shopinvader#178]
Since the merge of https://github.com/akretion/odoo-shopinvader/pull/167, products modification raise access errors on shopinvader.product read on backend_id during url_key computation.

The product is shared between multiple companies, the user belongs to company A, but shopinvader links are on company B.

As I don't know so much the project, I need some advice here. 

My instinct would have lead me to change url_key compute_sudo to True. Having done this, no more error on product modification.

@sebastienbeau @lmignon @Cedric-Pigeon

**Comment by rousseldenis** [comment]
As multicompany processes are always critical ones, should we add some tests on #167 ?

**Comment by rousseldenis** [comment]
PR is here https://github.com/akretion/odoo-shopinvader/pull/179

**Comment by sebastienbeau** [comment]
Fixed
