### ISSUE TITLE
IceCat connector

### ISSUE THREAD

**Issue by sebastienbeau** [shopinvader/odoo-shopinvader#20]
Creating an icecat connector for having a huge demo datastore

we can be inspired by 

https://pypi.python.org/pypi/django-icecat
http://pyicecat.readthedocs.io/en/latest/IceCat.html
https://github.com/Vauxoo/addons-vauxoo/tree/7.0/product_icecat
https://github.com/openlabs/nereid-catalog-icecat

**Comment by simahawk** [comment]
still valid?
