### ISSUE TITLE
Problem when installing requirements.txt of odoo-shopinvader

### ISSUE THREAD

**Issue by guillermm** [shopinvader/odoo-shopinvader#227]
Hello I wanted to know if it has changed the route or what happens?
Because when trying to install the Locomotivecms connector, I require that repository that is in the         [odoo-shopinvader/requirements.txt](https://github.com/akretion/odoo-shopinvader/blob/10.0/requirements.txt#L10)

when I install the requirement this shows me an error:

![captura_01](https://user-images.githubusercontent.com/18652795/46909112-ebe71e80-cef2-11e8-9125-046f9a16b98f.png)

and when I'm in odoo tried to install, I get this error:

![captura_02](https://user-images.githubusercontent.com/18652795/46909151-631cb280-cef3-11e8-8fba-4c058fcfdbb6.png)

Could you help me to continue the installation?

Thanks,

**Comment by hparfr** [comment]
Hi,

I don't know why the first line of pip install is "Collecting https://github.com/akretion/odoo-shopinvader...".
It should be something like 
```sh
odoo-shopinvader$ pip install -r requirements.txt 
Collecting slugify (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7b/89/fbb7391d777b60c82d4e1376bb181b98e75adf506b3f7ffe837eca64570b/slugify-0.0.1.tar.gz
Collecting cerberus (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/90/31/e30784a1f9a4b46875cfed1c9f806c188e2181e7ba3b568e81e7b0bc5718/Cerberus-1.2.tar.gz
Collecting algoliasearch (from -r requirements.txt (line 3))
...
```
Please ensure your are in python2 virtualenv and you are using pip through python2.

You can also try to install interactively the required libraries.

Specifically, locomotive-cms  can be installed like this : 
```sh
pip install -e git://github.com/akretion/locomotivecms-python-client.git#egg=locomotivecms

```
