### ISSUE TITLE
[EBS/Future] Shopinvader EBS support hooks

### ISSUE THREAD

**Issue by blaggacao** [shopinvader/odoo-shopinvader#265]
Some companies use an Enterprise Service Bus decoupled from the Odoo ecosystem.
Reasons might be:

- Observability
- Decoupling / scaling
- Monitoring
- API Monetization
- etc.

There must be a way to provide such hook in shopinvader so that an EBS can hook in and synchronize data to such external system  (as algolia, external content stores, etc).

Such hook would be somewhere before calling a job and rather deviate to trigger a webhook for the purpose of triggering the desired synchronization in the ESB.

I would wish this can be kept in the back of the mind as a use case possibly worth supporting. Also I would be grateful for conceptual hints on where to find the right place for changing this behavior in custom modules.

Some [screenshot](http://nimb.ws/uNv45X) for the dear reader who is not so familiar with en EBS system.

**Comment by simahawk** [comment]
@blaggacao is this still relevant?
Is not clear to me what you need that you cannot achieve now by hooking to existing hooks.
Any particular one missing?

**Comment by blaggacao** [comment]
Thanks for the follow up. I'll close.
