### ISSUE TITLE
Generic concept of sale.shop or sale.channel

### ISSUE THREAD

**Issue by sebastienbeau** [shopinvader/odoo-shopinvader#429]
The more I think about e-commerce and the fact that we can sale on several channel (amazon, c-discount, own site...), the more I think we should introduce a concept of "sale.channel" or "sale.shop" that can be "_inherits" by shopinvader.backend and same for backend in lengow connector.

**Comment by simahawk** [comment]
@sebastienbeau can you clarify a bit more purpose and how it should impact current state?
