### ISSUE TITLE
[10.0] Login create a new empty cart

### ISSUE THREAD

**Issue by acsonefho** [shopinvader/odoo-shopinvader#432]
**Current behavior**
When you login, a new empty cart is created. (Only if this user doesn't have one already in draft).

**Issue**
I think it's an issue (or undesired behavior) because as the user doesn't add anything into the basket, it shouldn't create a cart for nothing.

**How to reproduce**
- Check into backend how many existing carts you have;
- Go on the shopinvader website (don't browse any product);
- Create a new user account;
- Refresh your carts into the backend;
- You should have one more (related to the new user);
- Now you can delete this empty cart;
- Logout from the website;
- Login again;
- Check carts into backend => The empty cart is again created!
=> Each time a user login (without existing cart), a new one is created.

**Technically**
I already investigate a little bit about the origin of this behavior:
The `_get_and_assign_cart()` is called after each `sign_in()` (customer service). And this first function call the `_get()` on the cart service. This one create an empty cart if no current cart.
https://github.com/shopinvader/odoo-shopinvader/blob/10.0/shopinvader/services/customer.py#L76

`customer service => sign_in() => _assign_cart_and_get_store_cache() => _get_and_assign_cart()`

**Comment by acsonefho** [comment]
@lmignon What do you think about that?
Thank you

**Comment by lmignon** [comment]
Indeed, . _get is now designed to always return a cart... (if none is found, a new one is created) We must think further on the expected behavior...

**Comment by lmignon** [comment]
merged into 10.0 and 12.0
