### ISSUE TITLE
[RFC] shopinvader_lead: Add (configurable) tags

### ISSUE THREAD

**Issue by rousseldenis** [shopinvader/odoo-shopinvader#456]
The idea could be adding configurable tags in backend to be added when creating lead in Odoo. 

For instance, the aim would be differenciating leads that come from website and from other sources.

@sbidoul @sebastienbeau @lmignon

**Comment by sbidoul** [comment]
Or better, some sort of integration between `shoinvader_lead` and `utm.mixin` (of which `crm.lead` inherits).

That requires a bit more investigation, but it's definitely useful to have a way to integrate shopinvader with Odoo marketing modules.

Typical use case: you do a marketing campaign which direct customers to creates lead from the shopinvader website. You want the tracking information that was set in the campaign to be stored on the new leads. See for instance the `tracking_fields()` method in Odoo.

To begin with, configuring a default source and medium for new leads on the shopinvader backend can be enough.
