### ISSUE TITLE
Products wishlist

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#457]
## Goal
Provide wishlist feature + ability to create different kinds of lists.

## Solution
Start from
~~https://github.com/OCA/sale-workflow/blob/11.0/sale_product_set_variant/~~ 
https://github.com/OCA/sale-workflow/blob/12.0/sale_product_set
which already allows to define sets of products and convert them to SO lines.
Add endpoints for retrieving, searching and converting to cart.

### `sale_wishlist` module in OCA/sale-workflow

1. ~~Migrate sale_product_set_variant/ to v12 (WIP https://github.com/OCA/sale-workflow/pull/813)~~
2. Add `typology` field to `product.set`, Selection, 1 value for now: "default"
3. Add `partner_id` field to `product.set`
4. in the wizard, validate partner w/ SO partner, if valued
5. add smart button on partner -> jump to lists (add specific filter to search view)

### `shopinvader_wishlist`

1. add `product.set.typology` "wishlist"
2. add `backend_id` to `product.set` add wizard
3. move lines retrieval to `get_lines` in base implementation and override it in our code to filter our lines using product check method defined in https://github.com/shopinvader/odoo-shopinvader/issues/455 and filter our lines not allowed
4. add a service to expose wishlists that filters on such typology + current partner + exclude anon users (GET + SEARCH)
5. add endpoint `/wishlist_add_to_cart/$ID` which gets current cart and call `product.set` wizard passing cart_id (sale order id)

Aggregator issue: #452

**Comment by simahawk** [comment]
1st step: sale_wishlist https://github.com/OCA/sale-workflow/pull/994
I've change some details: 
* partner_id is in sale_product_set
* typology "wishlist" is in sale_wishlist

**Comment by simahawk** [comment]
another change: we don't need _variant as we rely on single products

**Comment by simahawk** [comment]
@lmignon one more doubt regarding the specs we defined: is it really needed to call the wizard to add wishlist items to cart?
The cart service will take care of updating a line if the product is already there. The wizard won't.
Also, the wizard does a lot of things to respect sequences etc -> we don't need it in the cart.
The cart now already checks if the product is allowed -> no need to add an extra override to validate lines, no need to specify a backend. 

I'd say: we should loop on set lines and use `cart.add_item` directly.
I'm not sure why thought about it... any strong argument against my proposal as far as you remember?

**Comment by lmignon** [comment]
@simahawk The logic called by the service must remains accessible from Odoo.  An user using Odoo should be able to manually apply a wishlist defined by a customer from within odoo. The service layer should not provides business logic...

**Comment by simahawk** [comment]
@lmignon I see your point but the cart service has its own logic and for a good reason. If we don't use it we still have to improve sale_product_set because it will have a behavior that is no expected by an e-commerce feature (eg: duplicating product lines in the cart). I'd like not to add extra logic.
I'm not sure is worth it in this case :thinking: 

EDIT: probably we should consider sale_product_set buggy in this regard. Why would you want to add more than one line for the same product? The only reason I could think of is that they could have a different discount. Hence, if we go w/ this improvement, shall we add an optional flag to "Update existing lines if any"?

**Comment by rousseldenis** [comment]
> another change: we don't need _variant as we rely on single products

Do I understand that user cannot define wishlist on a particular variant of product (Color, size, or...)? IMHO this as to be implemented...

**Comment by simahawk** [comment]
@rousseldenis nope. `sale_product_set` already links a `product.product`. `sale_product_set_variant` adds a template field + the possibility to add several variants per line and hides `product_id`. This feature, for me, is totally useless for the wishlist case. When me and Laurent discussed about this implementation we gave for granted that the base module deals only w/ the template but it's not.

**Comment by rousseldenis** [comment]
> @rousseldenis nope. `sale_product_set` already links a `product.product`. `sale_product_set_variant` adds a template field + the possibility to add several variants per line and hides `product_id`. This feature, for me, is totally useless for the wishlist case. When me a Laurent discussed about this implementation we gave for granted that the base module deals only w/ the template but it's not.

Ok, I see. The module name 'sale_product_set_variant' is a little bit confusing...

**Comment by simahawk** [comment]
Had a call w/ Laurent, outcome: 
1. ignore _variant (we could just add an issue regarding its bad implementation)
2. add a flag in product.set.add to update or ignore existing lines: if true, it ignores existing products  (default false)

**Comment by simahawk** [comment]
FTR this is implemented already in v12 and v13 :tada:
