### ISSUE TITLE
Q: Product multi-category?

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#462]
Hello guys :)

In std Odoo shop you can apply different public product categories on a product.
Here I see https://github.com/shopinvader/odoo-shopinvader/tree/12.0/shopinvader_multi_category but seems not migrated yet. What's the plan? I cannot find it.
Very likely we'll need this feature so better to know the common path ;)

Thanks!

CC @sebastienbeau @lmignon @sbidoul

**Comment by lmignon** [comment]
Hi @simahawk,

This addon is not yet migrated since our client on V12 don't need it. In v12, product.public.category comes with website_sale. IMO we should stay with product.multi.category for shopinvader.

Regards

lmi

**Comment by simahawk** [comment]
@lmignon hmm am I wrong or it does not provide the same feature?
I know that `product.public.category` comes from `website_sale`, unfortunately :sob: 
The point is that it adds another layer for the categories so that you can handle internal and website categories separately (imagine you don't want to publish them all or you want to display them w/ a different name).
With `shopinvader_multi_category` - which relies on `product_online_category` + `product_multi_category` - you don't have this.
Also, I see there's "type" field on the category but this is not used to if not to filter selectable categories.
How is/was this supposed to work?

**Comment by hparfr** [comment]
I have started the v12 migration of shopinvader_multi_category here #605
