### ISSUE TITLE
RFC make search engine locomotive export settings generic

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#466]
@lmignon the piece of code you put [here](https://github.com/shopinvader/odoo-shopinvader/blob/12.0/shopinvader_locomotive_elasticsearch/component/shopinvader_site_export_mapper.py) in `shopinvader_locomotive_elasticsearch` seems to be the same that can be used to export setting for algolia (and any other SE) because they are peculiar to locomotive plugin.

Being generic and being strictly tied to the shopinvader plugin in locomotive which relies on having a search engine I think we can move this code to `shopinvader_locomotive` and delegate to specific modules the overrides. 

Indeed the only thing that might change seems to be the main key of settings dict: "algolia" or "elasticsearch".

**Comment by lmignon** [comment]
@simahawk That makes sens to move this code into `shopinvader_locomotive` and find a way to provide the key into the specific addons .

**Comment by simahawk** [comment]
@lmignon there you go https://github.com/shopinvader/odoo-shopinvader/pull/477

**Comment by simahawk** [comment]
merged
