### ISSUE TITLE
RFC Merge locomotive settings schema fields all in once

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#490]
Use case: add a new field to the schema https://github.com/shopinvader/odoo-shopinvader/pull/476
ATM you cannot simply export new data to locomotive because you need that field to be present in its metafields schema.

IMO we should have only one bucket for such settings (eg: odoo_settings or erp_settings) which contains all the settings we need (eg: available_countries, languages, currencies, etc)
This way, no matter what we export, we don't have to do anything on the schema of the locomotive site (which is quite fragile in case of data deployment).

As long as we don't implement #489 I propose we add a flag the backend "Wrapped locomotive settings" to wrap the content of the export only if we already have an up top date locomotive instance.

@lmignon @sebastienbeau I'd like to hear your opinion :)

**Comment by lmignon** [comment]
@simahawk I like this idea. BUT we must document the changes and explain how an existing website can be migrated.

**Comment by simahawk** [comment]
@lmignon as you mentioned in #489 we are already reading existing settings and we can check what's available there. We could rely on it instead of adding a new flag.
I totally agree: this must be documented properly.

**Comment by lmignon** [comment]
@simahawk Can you check that if we export unknow settings to locomotive these are ignored. I've the feeling that the schema into locomotive is only used to allow the edition of these settings from within the admin site.

**Comment by simahawk** [comment]
had a call w/ @sebastienbeau yesterday: we agreed on wrapping settings only if the settings key is found on the existing instance (even if using "reset").
To keep existing instances safe, we can still push a copy of old info to the old static metafields.

**Comment by simahawk** [comment]
@lmignon you were right: apparently you can send whatever you want, locomotive won't complain.
In my opinion we should still wrap settings but seems is not fundamental ATM.
CC @sebastienbeau
