### ISSUE TITLE
Installable issue after v13 update

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#492]
@lmignon we have a big issue with this commit https://github.com/shopinvader/odoo-shopinvader/commit/0315f7a3c1fa6944aeafd33c961b7217ba563d93
it sets all modules or many of them as not installable :fearful: 
Am I missing anything? :thinking:

**Comment by simahawk** [comment]
apparently a bad target for v13 that landed on v12

**Comment by lmignon** [comment]
Indeed. Thank you for your help to fix this issue. The branch 12.0 is know reset at the last commit before the merge....
