### ISSUE TITLE
RFC Support additional contact data on customer endpoint

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#502]
**Usecase**
You are registering a company but you want to provide a contact as well. 

**Today**
You cannot, you have to wait for the whole registration to finish, log in, add addresses (which are not contact

**Proposal**
Add support for all `res.partner:type` options via prefixes.
We can loop on them and inject all keys supported for addresses prefixed by `contact_` or `invoice_` or `delivery_` etc.
If these keys are found a new child partner is created w/ proper type.

**Comment by sebastienbeau** [comment]
addresses[0]['type']=delivery
addresses[0]['name']=dupond

addresses[1]['type']=invoicing
addresses[1]['name']=durant

addresses[2]['type']=invoicing
addresses[2]['name']=simone

addresses[3]['type']=contact
addresses[3]['name']=thibault

**Comment by simahawk** [comment]
sounds good as we said :)

**Comment by simahawk** [comment]
1. we add a flag "is admin user"
2. the customer gets created
3. if one of the addresses is admin -> create a new user on locomotive via `shopinvader_locomotive`
