### ISSUE TITLE
Missing cart after sign in 

### ISSUE THREAD

**Issue by sebastienbeau** [shopinvader/odoo-shopinvader#555]
Running the ruby integration test I detect that the cart is missing after the sign in 
https://github.com/shopinvader/locomotive-shopinvader/blob/v4.0.x/spec/integration/server/auth_spec.rb#L99

I will investigate more

**Comment by rousseldenis** [comment]
> Running the ruby integration test I detect that the cart is missing after the sign in
> https://github.com/shopinvader/locomotive-shopinvader/blob/v4.0.x/spec/integration/server/auth_spec.rb#L99
> 
> I will investigate more

@sebastienbeau I don't know if this is linked but you cannot log in with two different browsers and get your current cart after second log in.
