### ISSUE TITLE
Product wishlist metadata by user

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#574]
Related to https://github.com/shopinvader/odoo-shopinvader/issues/457

We must be able to determine if a product stays in a customer's wishlist or not on client side.
How can we handle this?

If we still don't want to call odoo when we load the product page, I think that the only way is to have a specific index in the search engine that stores wishlist metadata.
Each record would be a wishlist w/ this params:

* id
* user_email
* products (list of SKU)
* name (maybe a dict w/ translations, to not have 1 index per each language)

This way you can:

* lookup quickly all the wishlists w/out calling Odoo (account -> wishlists) when you don't modify them
* check if a product is included in one or more wishlists

@lmignon @rousseldenis @sebastienbeau your input is much appreciated.

**Comment by lmignon** [comment]
@simahawk All this makes sens....

> name (maybe a dict w/ translations, to not have 1 index per each language)

The wishlist name is translatable ?????

**Comment by simahawk** [comment]
> The wishlist name is translatable ?????

actually not, I went by memory :sweat_smile: One thing less to take care of :)

Regarding the lang we have some constraints tho, because it's a required field for indexes. 

See 
https://github.com/OCA/search-engine/blob/12.0/connector_search_engine/models/se_index.py#L22
https://github.com/shopinvader/odoo-shopinvader/blob/13.0/shopinvader_search_engine/models/se_index.py#L18

In theory having a lang on this index should be useless. Anyway, let's consider we stick to current behavior. 

We'll have to determine the language to be used and we should be able to pass to the client the index name; the complete name otherwise is going to use the current lang to compute the name and won't find anything.

Otherwise, we assume multilang is going to be supported on wishlists as well and we export multilang settings as we do for existing indexes. Then the client will use the only index available as fallback in case it does not find a name matching current lang.

What do you think?

**Comment by hparfr** [comment]
Everything in the SE is more or less public. Isn't it a concern about user privacy ?

**Comment by simahawk** [comment]
you are right but we can simply use something else instead of the email (partner_id or an hash or something else). It seems good at least for a 1st version.

**Comment by lmignon** [comment]
@simahawk IMO we should support indexes without lang..

**Comment by simahawk** [comment]
Quick wrap up of recent call w/ @sebastienbeau and @thibaultrey .
We are going to simplify this a lot in a way that will be compatible w/ future redis integration (or whatever advanced caching sys we'll have).

On odoo side, we sync on the partner a mapping of product -> wishlist ids and a mapping of whishlist id -> whishlist names. Something like:

```py
wishlist_info = {
    "products": {
        pid1: [1, 2, 3] # wishlist ids,
        pid2: [1, 2, 3] # wishlist ids,
        pid3: [1, 2, 3] # wishlist ids,
    }
    "wishlists": {
        1: {"name": "Wishlist 1"},
        2: {"name": "Wishlist 2"},
    }
}
```
This will be pushed as json on the customer/user record on locomotive **synchronously** every time the list of products on a wishlist changes.
