### ISSUE TITLE
All travis builds fail due to a problem with SqlAlchemy

### ISSUE THREAD

**Issue by Cedric-Pigeon** [shopinvader/odoo-shopinvader#586]
sample: https://travis-ci.org/github/shopinvader/odoo-shopinvader/jobs/663994375?utm_medium=notification&utm_source=github_status

No merge are possible in such situation.

I tried several way to solve without any success.

Could anyone help me?

@hparfr @sebastienbeau @simahawk @lmignon @sbidoul

**Comment by hparfr** [comment]
I have this one too.

May be it's related to this https://github.com/pypa/pip/issues/6264

**Comment by sbidoul** [comment]
This is the reason I made https://github.com/OCA/maintainer-quality-tools/pull/646

**Comment by sbidoul** [comment]
Let's see: https://github.com/shopinvader/odoo-shopinvader/pull/587

**Comment by Cedric-Pigeon** [comment]
Solved by https://github.com/shopinvader/odoo-shopinvader/pull/589
