### ISSUE TITLE
[IMP] sale_promotion_rule always update write_date even if nothing change

### ISSUE THREAD

**Issue by acsonefho** [shopinvader/odoo-shopinvader#590]
Currently, when we have to re-check every days every carts to ensure the promotion is not expired (by a cron).

It cause some incompatibility with module `shopinvader_cart_expiry` and `shopinvader_pending_cart_reminder` because these 2 use the `write_date` of the cart to do the behaviour..

So for these 2 modules, the cart is updated every, that means:
- `shopinvader_cart_expiry`: the cart doesn't reach the expiration date so it's never deleted;
- `shopinvader_pending_cart_reminder`: the cart doesn't reach the reminder date so no reminder.

This issue is caused by the `compute_promotions(...)` who drop existing promotions to re-generate them (if still available). So the write date is updated every day (by the cron).
https://github.com/OCA/sale-workflow/blob/10.0/sale_promotion_rule/models/sale_promotion_rule.py#L263

Instead of creating a glue module (https://github.com/shopinvader/odoo-shopinvader/pull/581) for each module who is using this `write_date`, I think the best approach is to detect changes on the cart itself (for example: do not update the cart during `compute_promotions(...)` if nothing change).

Others ideas are welcome!

**Comment by acsonefho** [comment]
@Cedric-Pigeon if you want to give more details, you're welcome.
@sebastienbeau if you have an idea about this?

Thanks!

**Comment by Cedric-Pigeon** [comment]
@simahawk if you are inspired... ;-)

**Comment by Cedric-Pigeon** [comment]
I think the best would be to base shopinvader_cart_expiry and shopinvader_pending_cart_reminder processes on another information than the write_date.
The question is which one?

**Comment by Cedric-Pigeon** [comment]
Could we imagine to set an event listener on cart services (update, add_item, update_item and delete_item) to set a date field `last_customer_update` ?

**Comment by sebastienbeau** [comment]
I thinks it's a good and simple idea to add a last_customer_update date.
This can be done in the shopinvader module (updated by update, add_item, update_item....).
Then every module can use this date without ugly glue module

**Comment by sebastienbeau** [comment]
we can simply add a method _update_customer_date in cart service and then call it from the different endpoint

**Comment by Cedric-Pigeon** [comment]
The idea would be to have a property directly from the controller to propagate everywhere in the code. Then I would override write method and update `last_customer_update` if the property is set to True.
The main advantage is that this property will be useable for all objects and not only the cart.

**Comment by rousseldenis** [comment]
> The idea would be to have a property directly from the controller to propagate everywhere in the code. Then I would override write method and update `last_customer_update` if the property is set to True.
> The main advantage is that this property will be useable for all objects and not only the cart.

A dedicated inheritable component for that behaviour ?

**Comment by Cedric-Pigeon** [comment]
not really, the idea is a property `called_from_rest` accessible within the context from everywhere.

**Comment by sebastienbeau** [comment]
If we do such thing maybe we should have an Mixin

```
class TrackExternalUpdate(models.AbstractModel):
  last_external_update_date = field.Datetime()

  def is_called_from_rest(...)
    return self._context.get('called_from_rest', False)

  def write..
      if self.is_called_from_rest():
          last_external_update_date = ...
       return super...

  def create ...
      if self.is_called_from_rest():
          last_external_update_date = ...
     return super...
```

**Comment by Cedric-Pigeon** [comment]
I'll work on PR tomorrow. Stay tuned ;-)

**Comment by simahawk** [comment]
I agree w/ Seb, I was thinking about something similar ages ago :smile: 
Regarding the ctx key: IMO it should be set always in the env.context of shopinvader request and why not in base_rest (eg: `rest_request=True` in base_rest + `shopinvader_request=True` in shopinvader).

**Comment by Cedric-Pigeon** [comment]
@simahawk yes it was exactly my intends but not sure to include it in base_rest
