### ISSUE TITLE
Shopinvader: exclude location from online stock

### ISSUE THREAD

**Issue by Cedric-Pigeon** [shopinvader/odoo-shopinvader#600]
Currently on a shopinvader backend, we specify which **warehouse** we want to share the stock online.
I have a request from a customer who wants to exclude 1 or 2 locations from the online stock.
Any idea to do it easily?

**Comment by rousseldenis** [comment]
This could be done adding a field restricting the locations (many2many), and adding those locations to context when evaluating stock_field

**Comment by Cedric-Pigeon** [comment]
@rousseldenis yes thanks as discussed I missed the possibility to set a domain in the context
