### ISSUE TITLE
RFC Filter products by customer

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#709]
We need to filter products by customer (eg: products produced / sold only for specific customer).

Easy option: push `partner_ids` (as a list of res.partner IDS) to the product index and filter products by partner id on the search engine.

Tricky option: use filters, sync them to frontend and retrieve allowed products from there.

@sebastienbeau @lmignon @hparfr @Cedric-Pigeon feedback?

**Comment by hparfr** [comment]
Suggestion: can you base it on price lists ? There is already a lot of logic in price lists to link products against customers.

**Comment by simahawk** [comment]
@hparfr sounds like a good idea. I'll check this path, tnx!
