### ISSUE TITLE
shopinvader_partner_vat: Tests

### ISSUE THREAD

**Issue by rousseldenis** [shopinvader/odoo-shopinvader#744]
@sebastienbeau @PierrickBrun PR's on 10.0 branches are failing due to cassettes tests problems.

Can you check ?

**Comment by rousseldenis** [comment]
At first sight, I think this is because http VIES service is redirecting now all requests to https.

**Comment by sebastienbeau** [comment]
I have fixed all branch 10.0/12.0/13.0
