### ISSUE TITLE
[13.0] Missing translations

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#779]
@lmignon I've just realized [the commit for v13 migration](https://github.com/shopinvader/odoo-shopinvader/commit/b8fec48e92902880dd53830d0c07c9f154c1b764#diff-0aed17fe4bae2386141d34c1d3a20043) removed all translations from core module. Was it wanted?

**Comment by lmignon** [comment]
@simahawk :fearful: It's not intentional...

**Comment by simahawk** [comment]
@lmignon great :sweat_smile: 
Would you have time to restore it?
