### ISSUE TITLE
RFC Services' work context partner should be shopinvader.partner

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#787]
The partner in the context should always be the binding (shopinvader.partner) and not the real partner (res.partner).
A partner in the context of shopinvader, must always have a binding otherwise is not even found (except for addresses).
As per products, we often attach information to bindings because they are peculiar to a specific shop/backend.
This would ease lookup of bindings (we don't have to filter every time by backend when needed) and their custom data and some sort of isolation between backends.
OTOH is always easy to get the real partner from the partner via `record_id`.

CC @sebastienbeau @lmignon

**Comment by lmignon** [comment]
@simahawk That makes sens for me.

**Comment by simahawk** [comment]
1st step has been done here https://github.com/shopinvader/odoo-shopinvader/pull/817
`invader_partner` is set by the controller in the work context.
Next would be to make all services rely on it where it makes more sense.
