### ISSUE TITLE
Useless demo files in shopinvader_image

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#827]
shopinvader_image/demo/product_product_image_relation_demo.xml:1: [W7930(file-not-used), ]  not used from manifest
shopinvader_image/demo/storage_file_demo.xml:1: [W7930(file-not-used), ]  not used from manifest
shopinvader_image/demo/product_image_relation_demo.xml:1: [W7930(file-not-used), ]  not used from manifest
shopinvader_image/demo/storage_image_demo.xml:1: [W7930(file-not-used), ]  not used from manifest

@sebastienbeau @lmignon @acsonefho anyone knows if we still need them?

**Comment by lmignon** [comment]
If not used, should be removed...

**Comment by acsonefho** [comment]
These files have been removed from the manifest in this commit:
https://github.com/shopinvader/odoo-shopinvader/commit/3d3bef62e256495294473a0c60132f8f84c651c4

But they are loaded by the hooks:
https://github.com/shopinvader/odoo-shopinvader/blob/10.0/shopinvader_image/hooks.py#L10
