### ISSUE TITLE
[RFC] Shopinvader rating module

### ISSUE THREAD

**Issue by david-popa** [shopinvader/odoo-shopinvader#938]
We’re adding a product rating functionality in Shopinvader using the already available rating module (with mixin) from Odoo and we’ve identified 3 possible solutions that can extend the functionality beyond the product rating (partner rating, etc.):

1. Create another module for every model (shopinvader_rating_product, shopinvader_rating_partner, ...)

```
POST /product_rating/create
{
	“id”: 1,
	...
}
	
POST /partner_rating/create
{
	“id”: 1,
	...
}
```
2. Create only one module and add endpoints for each model (/create_product_rating, /create_partner_rating, …)
```
POST /rating/product_create
{
	“id”: 1,
	...
}

POST /rating/partner_create
{
	“id”: 1,
	...
}
```
3. Create only one service and add keys to specify the target (model name) which needs to be created
```
POST /rating/create
{
	“model”: “product”,
	“id”: 1,
	...
}

POST /rating/create
{
	“model”: “partner”,
	“id”: 1,
	...
}
```
We’d like some feedback on those 3 possible solutions and if you have another idea please don’t hesitate to share.

**Comment by simahawk** [comment]
IMO opt 3 would offer more flexibility.
