### ISSUE TITLE
[all versions] shopinvader: wrong delivery state

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#993]
ATM the state is hardcoded here https://github.com/shopinvader/odoo-shopinvader/blob/14.0/shopinvader/models/sale.py#L38 but seems wrong most of the time because when the order is done but not shipped yet, you already get "shipped".

The good solution seems to use https://github.com/OCA/sale-workflow/pull/1372.

@PierrickBrun any plan to integrate it here?

**Comment by sebastienbeau** [comment]
I agree !
